name: cleanup-registry

on:
  schedule:
    - cron: "0 17 * * *" # daily at 00:00 WIB (17:00 UTC)
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v3.1.0
        with:
          account: padel-technologies
          image-names: the-warden
          token: ${{ secrets.GITHUB_TOKEN }}
          cut-off: 30d # delete versions older than 30 days
          keep-n-most-recent: 5 # but always keep the 5 newest
